SELECT 
	base.*, 
	LAG(saving_account, -1) OVER (PARTITION BY customer_code ORDER BY date) AS saving_account_target, 
	LAG(guarantees, -1) OVER (PARTITION BY customer_code ORDER BY date) AS guarantees_target, 
	LAG(current_accounts, -1) OVER (PARTITION BY customer_code ORDER BY date) AS current_accounts_target, 
	LAG(derivada_account, -1) OVER (PARTITION BY customer_code ORDER BY date) AS derivada_account_target, 
	LAG(payroll_account, -1) OVER (PARTITION BY customer_code ORDER BY date) AS payroll_account_target, 
	LAG(junior_account, -1) OVER (PARTITION BY customer_code ORDER BY date) AS junior_account_target, 
	LAG(mas_particular_account, -1) OVER (PARTITION BY customer_code ORDER BY date) AS mas_particular_target, 
	LAG(particular_account, -1) OVER (PARTITION BY customer_code ORDER BY date) AS particular_account_target, 
	LAG(particular_plus_account, -1) OVER (PARTITION BY customer_code ORDER BY date) AS particular_plus_target, 
	LAG(short_term_deposit, -1) OVER (PARTITION BY customer_code ORDER BY date) AS short_term_deposit_target, 
	LAG(medium_term_deposit, -1) OVER (PARTITION BY customer_code ORDER BY date) AS medium_term_deposit_target, 
	LAG(long_term_deposit, -1) OVER (PARTITION BY customer_code ORDER BY date) AS long_term_deposit_target, 
	LAG(e_account, -1) OVER (PARTITION BY customer_code ORDER BY date) AS e_account_target, 
	LAG(funds, -1) OVER (PARTITION BY customer_code ORDER BY date) AS funds_target, 
	LAG(mortgage, -1) OVER (PARTITION BY customer_code ORDER BY date) AS mortgage_target, 
	LAG(pensions, -1) OVER (PARTITION BY customer_code ORDER BY date) AS pensions_target, 
	LAG(loans, -1) OVER (PARTITION BY customer_code ORDER BY date) AS loans_target, 
	LAG(taxes, -1) OVER (PARTITION BY customer_code ORDER BY date) AS taxes_target, 
	LAG(credit_card, -1) OVER (PARTITION BY customer_code ORDER BY date) AS credit_card_target, 
	LAG(guarantees, -1) OVER (PARTITION BY customer_code ORDER BY date) AS guarantees_target, 
	LAG(home_account, -1) OVER (PARTITION BY customer_code ORDER BY date) AS home_account_target, 
	LAG(payroll, -1) OVER (PARTITION BY customer_code ORDER BY date) AS payroll_target, 
	LAG(pensions_2, -1) OVER (PARTITION BY customer_code ORDER BY date) AS pensions_2_target, 
	LAG(direct_debit, -1) OVER (PARTITION BY customer_code ORDER BY date) AS direct_debit_target
FROM santander_tb base
