products:
  - "ind_ahor_fin_ult1"
  - "ind_aval_fin_ult1"
  - "ind_cco_fin_ult1"
  - "ind_cder_fin_ult1"
  - "ind_cno_fin_ult1"
  - "ind_ctju_fin_ult1"
  - "ind_ctma_fin_ult1"
  - "ind_ctop_fin_ult1"
  - "ind_ctpp_fin_ult1"
  - "ind_deco_fin_ult1"
  - "ind_deme_fin_ult1"
  - "ind_dela_fin_ult1"
  - "ind_ecue_fin_ult1"
  - "ind_fond_fin_ult1"
  - "ind_hip_fin_ult1"
  - "ind_plan_fin_ult1"
  - "ind_pres_fin_ult1"
  - "ind_reca_fin_ult1"
  - "ind_tjcr_fin_ult1"
  - "ind_valo_fin_ult1"
  - "ind_viv_fin_ult1"
  - "ind_nomina_ult1"
  - "ind_nom_pens_ult1"
  - "ind_recibo_ult1"

use_dates:
  - '2015-01-28'
  - '2015-02-28'
  - '2015-03-28'
  -
val_dates:
  - '2015-03-28'

test_dates:
  - '2016-06-28'

parameters:
  booster: "gbtree"
  max_depth: 8
  nthread: 4
  num_class: 24
  objective: "multi:softprob"
  silent: 1
  eval_metric: "mlogloss"
  eta: 0.1
  min_child_weight: 10
  colsample_bytree: 0.8
  colsample_bylevel: 0.9
  seed: 2018
  verbosity: 0