categorical_columns:
- employee_index
- country
- sex
- customer_relation_type
- residence_index
- foreigner_index
- spouse_index
- channel
- deceased_index
- addres_type
- province_name
- segmentation
customer_id: customer_code
date_columns:
- date
- first_holder_date
- primary_last_date
key_timestamp: date
numeric_columns:
- age
- customer_seniority
- household_gross_income
- new_customer_index
- primary_index
- customer_type
- activity_index
product_columns:
- saving_account
- guarantees
- current_accounts
- derivada_account
- payroll_account
- junior_account
- mas_particular_account
- particular_account
- particular_plus_account
- short_term_deposit
- medium_term_deposit
- long_term_deposit
- e_account
- funds
- mortgage
- pensions
- loans
- taxes
- credit_card
- securities
- home_account
- payroll
- pensions_2
- direct_debit
