services:
#  waitfordb:
#    image: dadarek/wait-for-dependencies
#    depends_on:
#      - db-server
#    restart: always
#    command: db-server:5432
  db-server:
    image: postgres:13.3
    container_name: ${DB_HOST}
    platform: 'linux/amd64'
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      #- $PWD/db_server:/var/lib/postgresql/data
      - mlflowv_postgres_sql:/var/lib/postgresql/data
      - $PWD/db_server:/data_backup

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - db-server

  tracking-server:
    container_name: mlflow-tracking
    build:
      context: tracking_server
      dockerfile: tracking_server/Dockerfile
      args:
        #- MYSQL_USER=${MYSQL_USER}
        #- MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - DB_HOST=${DB_HOST}
        - DB_NAME=${DB_NAME}
        - DEFAULT_ARTIFACT_ROOT=ftp://${FTP_USER_NAME}:${FTP_USER_PASS}@${HOST_IP}:10022/home/ftpusers
    image: mlflow-tracking:1.0
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - db-server

  ftp-server:
    image: stilliard/pure-ftpd:latest
    container_name: ftp-server
    ports:
      - "10022:21"
      - "30001-30010:30001-30010"
    volumes:
      - $PWD/ftp/data:/data_backup
      - mlflowv_postgres_ftp:/home/ftpusers

    environment:
      - PUBLICHOST=localhost
      - FTP_USER_NAME=${FTP_USER_NAME}
      - FTP_USER_PASS=${FTP_USER_PASS}
      - FTP_USER_HOME=/home/ftpusers
      - ADDED_FLAGS="--tls=2"
    restart: always

volumes:
  mlflowv_postgres_sql:
    external: false
    name: mlflowv_postgres_sql
  mlflowv_postgres_ftp:
    external: false
    name: mlflowv_postgres_ftp
