CREATE TABLE [dbo].[santander_raw_sample] (
    [Date]                              VARCHAR (MAX) NULL,
    [Customer_code]                     BIGINT        NULL,
    [Employee_index]                    VARCHAR (MAX) NULL,
    [Country_residence]                 VARCHAR (MAX) NULL,
    [Sex]                               VARCHAR (MAX) NULL,
    [Age]                               VARCHAR (MAX) NULL,
    [Date_first_held]                   VARCHAR (MAX) NULL,
    [New_customer_index]                FLOAT (53)    NULL,
    [Seniority_months]                  VARCHAR (MAX) NULL,
    [Customer_type]                     FLOAT (53)    NULL,
    [Last_date_primary_customer]        VARCHAR (MAX) NULL,
    [Customer_type_beginning_month]     FLOAT (53)    NULL,
    [Customer_relation_beginning_month] VARCHAR (MAX) NULL,
    [Residence_index]                   VARCHAR (MAX) NULL,
    [Foreigner_index]                   VARCHAR (MAX) NULL,
    [Spouse_index]                      VARCHAR (MAX) NULL,
    [Channel_join]                      VARCHAR (MAX) NULL,
    [Deceased_index]                    VARCHAR (MAX) NULL,
    [Address_type]                      FLOAT (53)    NULL,
    [Province_code]                     FLOAT (53)    NULL,
    [Province_name]                     VARCHAR (MAX) NULL,
    [Activity_index]                    FLOAT (53)    NULL,
    [Household_income]                  FLOAT (53)    NULL,
    [Segmentation]                      VARCHAR (MAX) NULL,
    [Saving_Account]                    BIGINT        NULL,
    [Guarantees]                        BIGINT        NULL,
    [Current_Accounts]                  BIGINT        NULL,
    [Derivada_Account]                  BIGINT        NULL,
    [Payroll_Account]                   BIGINT        NULL,
    [Junior_Account]                    BIGINT        NULL,
    [Más_particular_Account]            BIGINT        NULL,
    [particular_Account]                BIGINT        NULL,
    [particular_Plus_Account]           BIGINT        NULL,
    [Short_term_deposits]               BIGINT        NULL,
    [Medium_term_deposits]              BIGINT        NULL,
    [Long_term_deposits]                BIGINT        NULL,
    [e_account]                         BIGINT        NULL,
    [Funds]                             BIGINT        NULL,
    [Mortgage]                          BIGINT        NULL,
    [Pensions]                          BIGINT        NULL,
    [Loans]                             BIGINT        NULL,
    [Taxes]                             BIGINT        NULL,
    [Credit_Card]                       BIGINT        NULL,
    [Securities]                        BIGINT        NULL,
    [Home_Account]                      BIGINT        NULL,
    [Payroll]                           FLOAT (53)    NULL,
    [Pensions_2]                        FLOAT (53)    NULL,
    [Direct_Debit]                      BIGINT        NULL,
    [sequential_index]                  BIGINT        NULL
);
GO

