CREATE TABLE [dbo].[santander_raw_cleaned_sql] (
    [Date]                              DATE         NULL,
    [Customer_code]                     INT          NULL,
    [Employee_index]                    VARCHAR (20) NULL,
    [Country_residence]                 VARCHAR (20) NULL,
    [Sex]                               VARCHAR (20) NULL,
    [Age]                               INT          NULL,
    [Date_first_held]                   DATE         NULL,
    [New_customer_index]                INT          NULL,
    [Seniority_months]                  INT          NULL,
    [Customer_type]                     INT          NULL,
    [Last_date_primary_customer]        DATE         NULL,
    [Customer_type_beginning_month]     INT          NULL,
    [Customer_relation_beginning_month] VARCHAR (20) NULL,
    [Residence_index]                   VARCHAR (20) NULL,
    [Foreigner_index]                   VARCHAR (20) NULL,
    [Spouse_index]                      VARCHAR (20) NULL,
    [Channel_join]                      VARCHAR (20) NULL,
    [Deceased_index]                    VARCHAR (20) NULL,
    [Address_type]                      INT          NULL,
    [Province_code]                     INT          NULL,
    [Province_name]                     VARCHAR (30) NULL,
    [Activity_index]                    INT          NULL,
    [Household_income]                  FLOAT (53)   NULL,
    [Segmentation]                      VARCHAR (20) NULL,
    [Guarantees]                        INT          NULL,
    [Current_Accounts]                  INT          NULL,
    [Derivada_Account]                  INT          NULL,
    [Payroll_Account]                   INT          NULL,
    [Junior_Account]                    INT          NULL,
    [Más_particular_Account]            INT          NULL,
    [particular_Account]                INT          NULL,
    [particular_Plus_Account]           INT          NULL,
    [Short_term_deposits]               INT          NULL,
    [Medium_term_deposits]              INT          NULL,
    [Long_term_deposits]                INT          NULL,
    [e_account]                         INT          NULL,
    [Funds]                             INT          NULL,
    [Mortgage]                          INT          NULL,
    [Pensions_1]                        INT          NULL,
    [Loans]                             INT          NULL,
    [Taxes]                             INT          NULL,
    [Credit_Card]                       INT          NULL,
    [Securities]                        INT          NULL,
    [Home_Account]                      INT          NULL,
    [Payroll]                           INT          NULL,
    [Pensions_2]                        INT          NULL,
    [Direct_Debit]                      INT          NULL
);
GO

