INSERT INTO [dbo].[santander_cleaned_sample]
(
    date,
    customer_code,
    employee_index,
    country,
    sex,
    age,
    first_holder_date,
    new_customer_index,
    customer_seniority,
    primary_index,
    primary_last_date,
    customer_type,
    customer_relation_type,
    residence_index,
    foreigner_index,
    spouse_index,
    channel,
    deceased_index,
    addres_type,
    province_code,
    province_name,
    activity_index,
    household_gross_income,
    segmentation,
    saving_account,
    guarantees,
    current_accounts,
    derivada_account,
    payroll_account,
    junior_account,
    mas_particular_account,
    particular_account,
    particular_plus_account,
    short_term_deposit,
    medium_term_deposit,
    long_term_deposit,
    e_account,
    funds,
    mortgage,
    pensions,
    loans,
    taxes,
    credit_card,
    securities,
    home_account,
    payroll,
    pensions_2,
    direct_debit
)
SELECT 
    CAST(fecha_dato AS DATE) AS date,
    CAST(ncodpers AS INT) AS customer_code,
    TRY_CAST(ind_empleado AS CHAR) AS employee_index,
    TRY_CAST(pais_residencia AS CHAR) AS country,
    TRY_CAST(sexo AS CHAR) AS sex,
    COALESCE(TRY_CAST(age AS INT), -99) AS age,
    TRY_CAST(fecha_alta AS DATE) AS first_holder_date,
    COALESCE(TRY_CAST(ind_nuevo AS INT), -99) AS new_customer_index,
    COALESCE(TRY_CAST(antiguedad AS INT), -99) AS customer_seniority,
    COALESCE(TRY_CAST(indrel AS INT), -99) AS primary_index,
    TRY_CAST(ult_fec_cli_1t AS DATE) AS primary_last_date,
    COALESCE(TRY_CAST(indrel_1mes AS INT), -99) AS customer_type,
    TRY_CAST(tiprel_1mes AS CHAR) AS customer_relation_type,
    TRY_CAST(indresi AS CHAR) AS residence_index,
    TRY_CAST(indext AS CHAR) AS foreigner_index,
    TRY_CAST(conyuemp AS CHAR) AS spouse_index,
    TRY_CAST(canal_entrada AS CHAR) AS channel,
    TRY_CAST(indfall AS CHAR) AS deceased_index,
    TRY_CAST(tipodom AS INT) AS addres_type,
    TRY_CAST(cod_prov AS INT) AS province_code,
    TRY_CAST(nomprov AS CHAR) AS province_name,
    COALESCE(TRY_CAST(ind_actividad_cliente AS INT), -99) AS activity_index,
    COALESCE(TRY_CAST(renta AS FLOAT), -99) AS household_gross_income,
    TRY_CAST(segmento AS CHAR) AS segmentation,
    COALESCE(TRY_CAST(ind_ahor_fin_ult1 AS INT), 0) AS saving_account,
    COALESCE(TRY_CAST(ind_aval_fin_ult1 AS INT), 0) AS guarantees,
    COALESCE(TRY_CAST(ind_cco_fin_ult1 AS INT), 0) AS current_accounts,
    COALESCE(TRY_CAST(ind_cder_fin_ult1 AS INT), 0) AS derivada_account,
    COALESCE(TRY_CAST(ind_cno_fin_ult1 AS INT), 0) AS payroll_account,
    COALESCE(TRY_CAST(ind_ctju_fin_ult1 AS INT), 0) AS junior_account,
    COALESCE(TRY_CAST(ind_ctma_fin_ult1 AS INT), 0) AS mas_particular_account,
    COALESCE(TRY_CAST(ind_ctop_fin_ult1 AS INT), 0) AS particular_account,
    COALESCE(TRY_CAST(ind_ctpp_fin_ult1 AS INT), 0) AS particular_plus_account,
    COALESCE(TRY_CAST(ind_deco_fin_ult1 AS INT), 0) AS short_term_deposit,
    COALESCE(TRY_CAST(ind_deme_fin_ult1 AS INT), 0) AS medium_term_deposit,
    COALESCE(TRY_CAST(ind_dela_fin_ult1 AS INT), 0) AS long_term_deposit,
    COALESCE(TRY_CAST(ind_ecue_fin_ult1 AS INT), 0) AS e_account,
    COALESCE(TRY_CAST(ind_fond_fin_ult1 AS INT), 0) AS funds,
    COALESCE(TRY_CAST(ind_hip_fin_ult1 AS INT), 0) AS mortgage,
    COALESCE(TRY_CAST(ind_plan_fin_ult1 AS INT), 0) AS pensions,
    COALESCE(TRY_CAST(ind_pres_fin_ult1 AS INT), 0) AS loans,
    COALESCE(TRY_CAST(ind_reca_fin_ult1 AS INT), 0) AS taxes,
    COALESCE(TRY_CAST(ind_tjcr_fin_ult1 AS INT), 0) AS credit_card,
    COALESCE(TRY_CAST(ind_valo_fin_ult1 AS INT), 0) AS securities,
    COALESCE(TRY_CAST(ind_viv_fin_ult1 AS INT), 0) AS home_account,
    COALESCE(TRY_CAST(ind_nomina_ult1 AS INT), 0) AS payroll,
    COALESCE(TRY_CAST(ind_nom_pens_ult1 AS INT), 0) AS pensions_2,
    COALESCE(TRY_CAST(ind_recibo_ult1 AS INT), 0) AS direct_debit
FROM [dbo].[santander_duplicated_sample];