CREATE TABLE [dbo].[santander_raw_first] (
    [fecha_dato]            VARCHAR (MAX) NULL,
    [ncodpers]              BIGINT        NULL,
    [ind_empleado]          VARCHAR (MAX) NULL,
    [pais_residencia]       VARCHAR (MAX) NULL,
    [sexo]                  VARCHAR (MAX) NULL,
    [age]                   VARCHAR (MAX) NULL,
    [fecha_alta]            VARCHAR (MAX) NULL,
    [ind_nuevo]             FLOAT         NULL,
    [antiguedad]            VARCHAR (MAX) NULL,
    [indrel]                FLOAT         NULL,
    [ult_fec_cli_1t]        VARCHAR (MAX) NULL,
    [indrel_1mes]           VARCHAR (MAX) NULL,
    [tiprel_1mes]           VARCHAR (MAX) NULL,
    [indresi]               VARCHAR (MAX) NULL,
    [indext]                VARCHAR (MAX) NULL,
    [conyuemp]              VARCHAR (MAX) NULL,
    [canal_entrada]         VARCHAR (MAX) NULL,
    [indfall]               VARCHAR (MAX) NULL,
    [tipodom]               FLOAT         NULL,
    [cod_prov]              FLOAT         NULL,
    [nomprov]               VARCHAR (MAX) NULL,
    [ind_actividad_cliente] FLOAT         NULL,
    [renta]                 FLOAT         NULL,
    [segmento]              VARCHAR (MAX) NULL,
    [ind_ahor_fin_ult1]     BIGINT        NULL,
    [ind_aval_fin_ult1]     BIGINT        NULL,
    [ind_cco_fin_ult1]      BIGINT        NULL,
    [ind_cder_fin_ult1]     BIGINT        NULL,
    [ind_cno_fin_ult1]      BIGINT        NULL,
    [ind_ctju_fin_ult1]     BIGINT        NULL,
    [ind_ctma_fin_ult1]     BIGINT        NULL,
    [ind_ctop_fin_ult1]     BIGINT        NULL,
    [ind_ctpp_fin_ult1]     BIGINT        NULL,
    [ind_deco_fin_ult1]     BIGINT        NULL,
    [ind_deme_fin_ult1]     BIGINT        NULL,
    [ind_dela_fin_ult1]     BIGINT        NULL,
    [ind_ecue_fin_ult1]     BIGINT        NULL,
    [ind_fond_fin_ult1]     BIGINT        NULL,
    [ind_hip_fin_ult1]      BIGINT        NULL,
    [ind_plan_fin_ult1]     BIGINT        NULL,
    [ind_pres_fin_ult1]     BIGINT        NULL,
    [ind_reca_fin_ult1]     BIGINT        NULL,
    [ind_tjcr_fin_ult1]     BIGINT        NULL,
    [ind_valo_fin_ult1]     BIGINT        NULL,
    [ind_viv_fin_ult1]      BIGINT        NULL,
    [ind_nomina_ult1]       FLOAT         NULL,
    [ind_nom_pens_ult1]     FLOAT         NULL,
    [ind_recibo_ult1]       BIGINT        NULL,
    [sequential_index]      BIGINT        NULL
);
